version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://dpg-cst3ied6l47c73ehtf4g-a.oregon-postgres.render.com:5432/contentflow
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      VITE_BASE_URL: http://localhost:8080
